### ISSUE TITLE
sqlite3.operationalerror on update transaction

### ISSUE THREAD

**Issue by schnipdip** [schnipdip/Raisensu#1]
File:

raisensu.py

Code:

`cursor.execute('''UPDATE ASSETS SET ? = '?' WHERE ID = ?''', (updateColumn, setValue, updateIndex))`

Return:

```
Traceback (most recent call last):
  File "main.py", line 149, in <module>
    update_asset()
  File "main.py", line 99, in update_asset
    cursor.execute('''UPDATE ASSETS SET ? = '?' WHERE ID = ?''', (updateColumn, setValue, updateIndex))
sqlite3.OperationalError: near "?": syntax error
```

**Comment by schnipdip** [comment]
Resolved:

The UPDATE SQL Statement will allow for substitution. 

Code Fix:

`sql_update = "UPDATE ASSETS SET {0} = '{1}' WHERE ID = {2}".format(updateColumn, setValue, updateIndex)`

**Comment by j-freimuth** [comment]
Well done on fixing it.
The question is if those parameters are handed over from the outside. If so, that's a SQL injection vulnerability. You always have to be careful with parameters from the outer world. So, I'd recommend combining both attempts.

You need to set the column name via format. But since columns are limited, you can check them manually. Just like this:

```python
columns = ["id", "name", "other_columns"]
if updateColumn not in columns:
    raise Exception("Attempt to update unknown column: {}".format(updateColumn)) # bonus points when you define your own exception for that
```

After that you can savely do this:

```python
sql_update = "UPDATE ASSETS SET {0} = ? WHERE ID = ?".format(updateColumn)
cursor.execute(sql_update, [setValue, updateIndex])
```


That should work and remove any SQL injection vulnerabilities.
